drop database if exists lego;
create database lego;
use lego;

create table theme (
    theme_id int primary key auto_increment,
    theme_name varchar(255) not null,
    theme_description varchar(500) not null,
    theme_url varchar(255) not null
);

create table blog (
 blog_id int primary key auto_increment,
 blog_title varchar(255) not null,
 blog_description varchar(500) not null,
 date_posted date,
 author varchar(255) not null
);

create table legoSet (
    set_id varchar(255) primary key,
    set_name varchar(255) not null,
    pieces int,
    price double,
    ages varchar(5),
    image_url varchar(255),
    set_theme_id int,
    set_description varchar(750),
    rating double,
    constraint fk_set_theme_id
        foreign key (set_theme_id)
        references theme(theme_id)    
);

create table legoMiniFigure (
    figure_id int primary key,
    figure_name varchar(255) not null,
    pieces int,
    image_url varchar(255),
    figure_theme_id int,
    constraint fk_figure_theme_id
        foreign key (figure_theme_id)
        references theme(theme_id)    
);

create table newsPost (
    post_id int primary key auto_increment,
    post_title varchar(255) not null,
    post_caption varchar(500) not null,
    date_posted date
);

 insert into theme (theme_name,theme_description,theme_url) values
    ('Star Wars', 'In a galaxy far, far away is a world full of adventures that pits good vs. evil as Star Wars™ fans join Luke Skywalker, Han Solo, The Mandalorian, Grogu and more to recreate favorite scenes from the series. Harness the Force to build epic ships and vehicles, awesome droids and iconic characters.', 'https://www.lego.com/cdn/cs/set/assets/blt0dface6e340fa9bb/StarWars-202301-Theme-Preview.jpg?fit=bounds&format=webply&quality=80&width=420&height=200&dpr=1.5'),
    ('Technic','LEGO® Technic™ sets provide an advanced and complex building experience based on real-life vehicles big and small like sportscars, motorcycles and construction vehicles. They’re packed full of authentic features like functioning gearboxes, wheels and axles. Come enjoy some happy Technic building!','https://www.lego.com/cdn/cs/set/assets/blt408a31a595941aae/Technic-202309-Theme-Preview.jpg?fit=bounds&format=webply&quality=80&width=420&height=200&dpr=1.5'),
    ('Ideas','LEGO® Ideas sets are wonderfully unique builds inspired by fans’ designs and voted on by fellow fans to become official sets. These imaginative creations come to life include iconic TV and movie favorites, distinctive structures, space exploration, musical instruments and more.','https://www.lego.com/cdn/cs/set/assets/blt01f936ee7fbaf1d2/Ideas-202307-Theme-Preview.jpg?fit=bounds&format=webply&quality=80&width=420&height=200&dpr=1.5'),
    ('Architecture','Capture the beauty and décor of some of the most remarkable landmarks around the world with LEGO® Architecture sets. From iconic city skylines to jaw-dropping historical structures, fulfill the passion of any architectural enthusiast with mindful builds of these impressive models.','https://www.lego.com/cdn/cs/set/assets/blta76c9d1ad23dc015/Architecture-202308-Theme-Preview.jpg?fit=bounds&format=webply&quality=80&width=420&height=200&dpr=1.5'),
    ('Marvel','The battle of good vs. evil continues with LEGO® Marvel sets for fans to recreate exciting movie scenes from the Marvel Cinematic Universe. Join favorites like the Guardians of the Galaxy, Ant-Man, Black Panther, Spider-Man, The Hulk and more in thrilling role-play adventures.','https://www.lego.com/cdn/cs/set/assets/blt769a5bd0a96b7435/Marvel-202307-Theme-Preview.jpg?fit=bounds&format=webply&quality=80&width=420&height=200&dpr=1.5'),
    ('Disney','Celebrate 100 years of magical wonder with LEGO® | Disney sets featuring iconic characters. Fans can relive memorable Disney scenes, build enchanting castles and recreate amusement park attractions. Join Mickey and Friends, Disney Princess characters and more for fun, imaginative play.','https://www.lego.com/cdn/cs/set/assets/blt9fff5f641676e13f/Disney-202307-Theme-Preview.jpg?fit=bounds&format=webply&quality=80&width=420&height=200&dpr=1.5'),
    ('Icons','Designed for a challenging yet rewarding building experience, LEGO® Icons sets showcase impressive landmarks, modular buildings, classic vehicles, pop culture favorites and beautiful home décor sets. Find your passion and immerse yourself in builds that are worthy to be displayed.','https://www.lego.com/cdn/cs/set/assets/blt893dcd6cfefefa90/Icons-202303-Theme-Preview.jpg?fit=bounds&format=webply&quality=80&width=420&height=200&dpr=1.5'),
    ('Harry Potter','Enter the magical world of LEGO® Harry Potter™ filled with spellbinding creativity for fans. Help Harry, Hermione, Ron and more take on the Dark Wizards as you recreate authentically detailed scenes from the series and build enchanting models to display. Channel your inner wizard!','https://www.lego.com/cdn/cs/set/assets/blt2867cab4175c4a5d/HarryPotter-202307-Theme-Preview.jpg?fit=bounds&format=webply&quality=80&width=420&height=200&dpr=1.5'),
    ('Duplo', 'When little ones have big imaginations, LEGO® DUPLO® building blocks unleash their creativity through developmental learning. These play sets put open-ended fun, self-expression and joyful exploration into young children’s hands. LEGO Duplo offers a wide range of themed sets',  'https://www.lego.com/cdn/cs/set/assets/blt172719fccb1f87a3/Duplo-202310-Theme-Preview.jpg?fit=bounds&format=webply&quality=80&width=420&height=200&dpr=1.5'),
	('City','Explore the bustling world of LEGO® City where there’s lots to do! Visit fun downtown destinations, play out exciting emergency services stories and discover new frontiers including the ocean and space. Build cool vehicles, take a ride on the train or put on exciting arena stunt shows.','https://www.lego.com/cdn/cs/set/assets/blt00a899a8f8197281/City-202307-Theme-Preview.jpg?fit=bounds&format=webply&quality=80&width=420&height=200&dpr=1.5'),
    ('Creator 3in1','LEGO® Creator 3in1 sets can inspire brilliant imaginative play with multiple builds in one! Detailed models can be taken apart and be rebuilt into whatever builders can dream up. Sets include realistic buildings, cool vehicles and awesome animals.','https://www.lego.com/cdn/cs/set/assets/bltb65203c9c0548ee3/Creator3in1-202310-Theme-Preview.jpg?fit=bounds&format=webply&quality=80&width=420&height=200&dpr=1.5'),
    ('LEGO® Education','Traditionally developed for school settings, LEGO® Education solutions ignite students’ natural curiosity and help them develop essential 21st century skills. These products aim to promote creativity, problem-solving skills, teamwork, deeper understandings.','https://www.lego.com/cdn/cs/set/assets/blte5374a1fe72e1f26/ThemeImage-202107-Education.jpg?fit=bounds&format=webply&quality=80&width=420&height=200&dpr=1.5'),
    ('NINJAGO®','There’s action-packed role-playing fun throughout LEGO® NINJAGO® sets filled with spinning ninjas, soaring dragons, powerful mechs and more. Construct stunningly detailed temples and cool vehicles as you battle it out between good vs. evil in endless story possibilities.','https://www.lego.com/cdn/cs/set/assets/blt79fac60aec014669/Ninjago-202306-Theme-Preview.jpg?fit=bounds&format=webply&quality=80&width=420&height=200&dpr=1.5'),
    ('Speed Champions','Ready, set, go! LEGO® Speed Champions give race car fans the chance to recreate mini versions of the world’s leading and best-known vehicles. Build and display these collectible model replicas from the likes of Ferrari, Aston Martin, Lamborghini, Dodge and Chevrolet.','https://www.lego.com/cdn/cs/set/assets/blt577d7db2eeb173be/SpeedChamps-202303-Theme-Preview.jpg?fit=bounds&format=webply&quality=80&width=420&height=200&dpr=1.5'),
	('LEGO® Super Mario™','Jump into the world of LEGO® Super Mario™ sets for interactive play in exciting adventures. Fans can build Starter Courses and Expansion Sets to recreate iconic locations, team up with Donkey Kong and his crew in the jungle and construct models for play and display.','https://www.lego.com/cdn/cs/set/assets/blt988d37bbaaee4774/LSM-202308-Theme-Preview.jpg?fit=bounds&format=webply&quality=80&width=420&height=200&dpr=1.5');

	insert into blog(blog_title,blog_description,date_posted,author) values
    ('Animal Crossing', 'I cannot wait for the new Animal Crossing x Lego collaboration!', '2023-10-10','legolover123'),
    ('BrickCon 2023 - Who is Ready for the Ultimate LEGO Convention?', 'The countdown to BrickCon 2023 is on! Who else is gearing up for this fantastic LEGO event? Share your plans, excitement, and tips for making the most of the convention. Who wants to connect and meet up!','2023-10-13','kraglehater'),
    ('LEGO Haul of the Day - Scored Some Rare Sets!','Just had an incredible haul day, and I cannot contain my excitement! Snagged a few rare and discontinued sets for a steal. Have you ever stumbled upon an unexpected LEGO treasure? Share your stories!','2023-10-14', 'legooooo'),
    ('Lego Movie','What did everyone think of the Lego Movie?','2023-10-20','anonymouslego'),
    ('Favorite set','What is everyone''s favorite set?','2023-10-22','legossss'),
    ('"LEGO in Education - How I Use Bricks for Learning','As an educator, I''ve been using LEGO to enhance learning in my classroom. Share your experiences with using LEGO for educational purposes and inspire fellow teachers and parents with creative ideas.','2023-10-14','legoteacher'),
    ('Movie Marathon!',' It''s movie night, and I''m gearing up for a LEGO movie marathon! Which is your favorite LEGO movie, and why? Let''s discuss the humor, creativity, and nostalgia these films bring to our lives.','2023-10-19','kragleornottokragle'),
    ('Holidays coming up!', 'I wonder what Lego has in store for the holidays this year :)','2023-10-13','randomlegopiece'),
    ('Brick Swap Time - Looking for Technic Pieces!','Hey everyone, I am on the hunt for some Technic pieces to complete my latest project. Anyone up for a trade? I have got a variety of bricks and minifigs to offer. How about we help each other out!','2023-10-14','milleniumfalcon');

	insert into legoSet (set_id, set_name, pieces, price, ages, image_url, set_theme_id, set_description, rating) values
    ('price_1O2y9RAu3cUStmz7JPjN8fnH','Millennium Falcon', 7541, 849.99, '16+', 'https://www.lego.com/cdn/cs/set/assets/blt95c35d4ed5665a49/75192.jpg?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5', 1, ' This amazing LEGO interpretation of Han Solo’s unforgettable Corellian freighter has all the details that Star Wars fans of any age could wish for, including intricate exterior detailing, upper and lower quad laser cannons, landing legs, lowering boarding ramp and a 4-minifigure cockpit with detachable canopy. ', 4.6),
    ('price_1O2y9uAu3cUStmz7RSkXQu91','AT-AT', 6785, 849.99, '18+', 'https://www.lego.com/cdn/cs/set/assets/blta7b7b825b6d4fc0a/75313_Prod.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5', 1, 'This is the AT-AT (75313) that every LEGO® Star Wars™ fan has been waiting for. This epic Ultimate Collector Series build-and-display model features posable legs and head, cannons with a realistic recoil action, rotating cannons, bomb-drop hatch and a hook to attach to Luke Skywalker’s line, just like in the Battle of Hoth.', 4.2),
    ('price_1O2yAMAu3cUStmz7gpDdMrCI','Venator-Class Republic Attack Cruiser', 5374, 649.99, '18+', 'https://www.lego.com/cdn/cs/set/assets/blt06c6593d8e8d1c13/75367.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5', 1, 'Spark memories of epic Clone Wars adventures with this LEGO® Star Wars™ Ultimate Collector Series version of the Venator-Class Republic Attack Cruiser (75367). Let your mind drift to a galaxy far, far away as you recreate authentic features such as the striking red stripes, command bridge and hangar containing a brick-built scale model of a Republic Gunship.', 4.7),
    ('price_1O2yAhAu3cUStmz7dinpaBFo','R2-D2', 2314, 239.99, '18+','https://www.lego.com/cdn/cs/set/assets/blt38e8915698af2d5f/75308.jpg?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5',1,'Relive classic Star Wars™ moments as you build this exceptionally detailed R2-D2 LEGO® droid figure. The brilliant new-for-May-2021 design is packed with authentic details, including a retractable mid-leg, rotating head, opening and extendable front hatches, a periscope that can be pulled up and turned, and Luke Skywalker’s lightsaber hidden in a compartment in the head.',4.5),
    ('price_1O2yAzAu3cUStmz7JWRalImL', 'Ferrari Daytona', 3778, 449.99, '18+','https://www.lego.com/cdn/cs/set/assets/bltb862bc546852bd71/42143.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5',2, 'From the LEGO® Technic™ Ultimate Car Concept series comes an impressive build for adult Ferrari fans. Enter a zone of total mindfulness as you recreate the features of the Ferrari Daytona SP3 model in classic red with chrome-painted rims. Then place it on display to admire the iconic rear and curved lines that make this 1:8 scale model so special.',4.2),
    ('price_1O2yBOAu3cUStmz7gOjPG3Za','Lamborghini Sián FKP 37',3696,449.99,'18+','https://www.lego.com/cdn/cs/set/assets/bltee88e5e65f00bd00/42115.jpg?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5',2,'Experience the unmistakable power and looks of the Lamborghini Sián FKP 37 as you become immersed in this LEGO® Technic™ building kit (42115). With superb detailing, the model car is a faithful representation of the original Sián FKP 37 in eye-catching lime green with golden rims.',4.0),
    ('price_1O2yBiAu3cUStmz7J9I9s3YX', 'Grand Piano', 3662, 399.99, '18+','https://www.lego.com/cdn/cs/set/assets/blt20c84b1ff55e3256/21323.jpg?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5',3,'Do you have a passion for music? Do you like to relax by focusing on a fun, hands-on project in your free time? If so, this incredible LEGO® Ideas Grand Piano model kit (21323) is just the creative activity for you.',4.3),
    ('price_1O2yC3Au3cUStmz7VCsGaRBF','Vincent van Gogh - The Starry Night',2316,169.99,'18+','https://www.lego.com/cdn/cs/set/assets/bltc6d87e5e7bacb3ae/21333.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5',3,'Build creativity. Build concentration. Build your own 3D LEGO® brick version of one of Vincent van Gogh’s most celebrated artworks, The Starry Night, which can be seen at The Museum of Modern Art (MoMA) in New York City. Discover innovative building techniques to capture Van Gogh’s swirling brushstrokes, and hang your completed masterpiece by the hook on a wall or display it freestanding. This wonderfully detailed LEGO Ideas model (21333) comes with an adjustable display arm on which the Vincent van Gogh minifigure can stand with his paintbrush, palette and easel.',4.8),
    ('price_1O2yCMAu3cUStmz79FB51Br0','Tree House',3036,249.99,'16+','https://www.lego.com/cdn/cs/set/assets/blt177e3adbf9069c6f/21318.jpg?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5',3,'Build, display and play with this intricately detailed, 3,036-piece LEGO® Ideas 21318 Tree House playset. A complex build for experienced LEGO builders that all the family will love to play with, it features a landscape base and 3 LEGO tree house cabins—a main bedroom, bathroom and kids’ room. The tree has interchangeable sets of green summer leaf elements and yellow and brown fall leaf elements—these and various plant elements on the base are all made from sustainable-plant-based polyethylene plastic—and the treetop and cabin roofs are removable to allow easy access. ',4.6),
    ('price_1O2yDXAu3cUStmz7qyHE5Fk3', 'LEGO® Ideas Fender® Stratocaster',1074,119.99,'18+','https://www.lego.com/cdn/cs/set/assets/blt76e8ec83e0664e81/21329.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5',3,'Create your own brick-built 1970s Fender® Stratocaster™ guitar and 65 Princeton® Reverb amplifier with this LEGO® Ideas set (21329). Recall the legendary musicians who have played a Stratocaster® as you recreate its iconic curves and add authentic details such as the posable whammy bar, pickup switch and tuning pegs.',4.4),
    ('price_1O2yDsAu3cUStmz7LkR5RPpX','New York City',598,59.99,'12+','https://www.lego.com/cdn/cs/set/assets/blte43eb44c1411b445/21028.jpg?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5',4,'Celebrate the architectural diversity of New York City with this detailed LEGO® brick model. The LEGO Architecture Skyline Collection offers models suitable for display in the home and office, and has been developed for all with an interest in travel, architectural culture, history and design.',4.3),
	('price_1O2yEJAu3cUStmz7kqccPz3I','London',468,39.99,'12+','https://www.lego.com/cdn/cs/set/assets/blt98d7ba0b6a8b2997/21034.jpg?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5',4,'Celebrate the architectural diversity of London with this detailed LEGO® brick model. The LEGO Architecture Skyline Collection offers models suitable for display in the home and office, and has been developed for all with an interest in travel, architectural culture, history and design. ',4.6),
    ('price_1O2yEfAu3cUStmz7T32YD5rI','Hulkbuster', 4049,549.99,'18+','https://www.lego.com/cdn/cs/set/assets/blte9c486327506d9fb/76210.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5',5,'LEGO® Marvel Hulkbuster (76210) captures the scale and power of the Hulkbuster MK44 from Marvel Studios’ Avengers: Age of Ultron. Standing over 20.5 in. (52 cm) tall and containing 4,049 pieces, this challenging and rewarding construction project is designed with adult enthusiasts in mind.',2.9),
    ('price_1O2yF0Au3cUStmz7CHNuXAUM','Sanctum Sanctorum',2708,249.99,'18+','https://www.lego.com/cdn/cs/set/assets/blt5157080434f0c032/76218.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5',5,'Capture the magic of Doctor Strange with the stunning LEGO® Marvel Sanctum Sanctorum (76218), a celebration of the Master of the Mystic Arts – designed with adult enthusiasts in mind.',4.5),
    ('price_1O2yFdAu3cUStmz7gTS2YEqM','Black Panther',2961,349.99,'18+','https://www.lego.com/cdn/cs/set/assets/blt6594e9e9614f362f/76215.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5',5,'Advanced, buildable model of King T’Challa.This detailed recreation features the almost life-size head, chest and hands of Black Panther, posed in the iconic Wakanda Forever salute. Both hands feature articulated fingers and detach from the main model to increase display possibilities.',3.8),
    ('price_1O2yG0Au3cUStmz7jrQPU54R','Disney Castle',4837,399.99,'18+','https://www.lego.com/cdn/cs/set/assets/blt4dbf45919a0034d4/43222.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5',6,'Share your love of Disney Princess characters and their partners with this LEGO® ǀ Disney: Disney Castle (43222) set. Based on several well-known Disney Princess movies, this detailed set showcases different rooms, classic Disney references, nostalgic details, plus a special time capsule commemorating 100 years of Disney movies, all in a unique castle designed for display. ',4.9),
    ('price_1O2yGNAu3cUStmz7V1ONODQl','Up House',598,59.99,'9+','https://www.lego.com/cdn/cs/set/assets/bltde655e8359417b7d/43217.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5',6,'Adventure awaits Disney fans aged 9 and up with this fun LEGO® ǀ Disney and Pixar ‘Up’ House (43217). The set that everyone will be talking about includes a detailed section of the iconic house with a chimney and balloons, 2 LEGO minifigures, a LEGO dog figure, a wilderness explorer backpack and an adventure book.',4.3),
    ('price_1O2yGjAu3cUStmz7UJooM2an','Walt Disney Tribute Camera',811,99.99,'18+','https://www.lego.com/cdn/cs/set/assets/blta0d2ef903df1c30c/43230.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5',6,'Showcase your passion for all things Disney with this eye-catching LEGO® ǀ Disney Walt Disney Tribute Camera (43230) set for adults. This detailed collectible set features a vintage-style movie ‘camera’ with a hinged back panel with a surprise and a film strip showing stills from 20 historic Disney movies, a director’s clapperboard with space for the 3 LEGO ǀ Disney minifigures, 2 LEGO animal figures and a multiplane camera with 3 printed screens showing how Disney’s The Old Mill short was made.',4.8),
    ('price_1O2yH6Au3cUStmz7v18uIAdG','LEGO® Titanic',9090,679.99,'18+','https://www.lego.com/cdn/cs/set/assets/bltb94632aeb971eb91/10294.jpg?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5',7,'Since the Titanic set sail on its fateful maiden journey in 1912, the famous ship has captured imaginations across the world. Now you can pay tribute to it with this colossal LEGO® Titanic (10294) collectible model building project.',4.8),
    ('price_1O2yHQAu3cUStmz7TBKytIEi','Orchid',608,49.99,'18+','https://www.lego.com/cdn/cs/set/assets/blt08ea230311e717b8/10311.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5',7,'Enjoy a mindful building project and create a beautiful plant display for your home with this LEGO® Orchid (10311) model building project for adults. Take your time crafting all the details of the white and pink flowers and the vase. Inspired by a real orchid, the model has 5 leaves at the base and 2 wandering air roots to create an authentic display. ',4.8),
    ('price_1O2yHgAu3cUStmz7kPsLBRxD','Bonsai Tree',878,49.99,'18+','https://www.lego.com/cdn/cs/set/assets/blta0f82238c7a41b0b/10281_alt4.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5',7,'The art of bonsai has captured the imaginations of tree lovers for centuries. Now you can celebrate this ancient art with the LEGO® Bonsai Tree model building kit. Enjoy a sense of calm as you carefully shape the bonsai tree model with either green leaves or pink cherry blossoms.',4.5),
    ('price_1O2yI5Au3cUStmz7QWsM82QF','Hogwarts™ Castle',6020,469.99,'16+','https://www.lego.com/cdn/cs/set/assets/blt2c408dc4fb192074/71043.jpg?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5',8,'Make the magic come alive at the LEGO® Harry Potter™ 71043 Hogwarts™ Castle! This highly detailed LEGO Harry Potter collectible has over 6,000 pieces and offers a rewarding build experience. It comes packed with highlights from the Harry Potter series, where you will discover towers, turrets, chambers, classrooms, creatures, the Whomping Willow™ and Hagrid´s hut, plus many more iconic features. ',4.7),
    ('price_1O2yIPAu3cUStmz7eeEuKbYa','Hogwarts™ Icons - Collectors Edition',3010,299.99,'18+','https://www.lego.com/cdn/cs/set/assets/blt93cb15446264f1b3/76391_alt2.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5',8,'This homage to the Wizarding World of Harry Potter features many iconic artifacts in a single, stunning model. There’s Harry’s wand and glasses; Ron’s chocolate frog; Hermione’s potion tray containing 5 bottles of potions and magical ingredients (including Gillyweed, Felix Felicis ‘liquid luck’ and Polyjuice); Tom Riddle’s diary; the Golden Snitch; and a school scarf (customizable to suit any Hogwarts™ House). On top of this enchanting ensemble sits Hedwig™ the owl, holding a much-coveted invitation to Hogwarts. ',4.8),
    ('price_1O2yIgAu3cUStmz7NbBadpWK','Gringotts™ Wizarding Bank – Collectors Edition',4801,429.99,'18+','https://www.lego.com/cdn/cs/set/assets/bltfbd377eafb67041a/76417.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5',8,'Be transported to the Wizarding World as you build this LEGO® Harry Potter™ Gringotts™ Bank – Collectors’ Edition (76417) set. Recreate the bank’s opulent foyer and mezzanine floor with a safe in the wall to store Hagrid’s secret letter. Construct a spiraling vault cart track with a mechanism that stops the cart at each of 3 underground vaults – including Bellatrix’s vault, which has a magical surprise inside! ',4.8),
    ('price_1O4q1mAu3cUStmz7a31k7hoL','Typewriter',2079,249.99,'18+','https://www.lego.com/cdn/cs/set/assets/blt505d24ad41366851/21327.jpg?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5',3,'Unplug from your digital life and recall simpler times as you build a LEGO® Ideas model of an old-fashioned typewriter (21327). The design is inspired by the classic typewriter used by the LEGO Group’s founder Ole Kirk Kristiansen, and it moves and sounds just like the real thing.',4.3),
    ('price_1O4q5JAu3cUStmz7sRq8iH4j','Jazz Quartet',1606,99.99,'18+','https://www.lego.com/cdn/cs/set/assets/blt51cfcb2db00dd939/21334.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5',3,'Get into your groove and compose a jazz masterpiece. Create your own LEGO® Ideas Jazz Quartet (21334) featuring brick-built figures of a pianist, bassist, trumpeter and drummer in dynamic poses, plus highly detailed buildable models of their instruments – a grand piano, double bass, trumpet and drum kit.',4.8),
    ('price_1O4qBIAu3cUStmz7ZUFn5Cq0','Thor''s Hammer',979,99.99,'18+','https://www.lego.com/cdn/cs/set/assets/bltd22f99034387c7ac/76209.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5',5,'Marvel enthusiasts will recognize this authentic recreation as Mjölnir, the magical weapon used to devastating effect by Thor throughout Marvel Studios’ 23-movie Infinity Saga. The 18 in. (46 cm) tall model of the iconic hammer rests securely on a stand with an information plate displaying the word ‘Mjölnir’ and the Infinity Saga logo. ',4.5),
    ('price_1O4qJvAu3cUStmz7ny27MUvK','PAC-MAN Arcade',2651,269.99,'18+','https://www.lego.com/cdn/cs/set/assets/blt74da473b5ba874fe/10323.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5',7,'This LEGO replica is loaded with retro design details and fun features, including a 4-way joystick and an illuminating coin slot. Turn the handle to activate a mechanical maze that simulates the classic chase between your favorite characters or open the back panel to view the mechanical elements. ',4.9),
    ('price_1O4qKQAu3cUStmz783Vm0vq4','Tranquil Garden',1363,99.99,'18+','https://www.lego.com/cdn/cs/set/assets/bltc1a3afc5b5af3287/10315.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5',7,'Based on a traditional Japanese garden, this buildable model includes an arched bridge, stream, koi carp, lotus flowers, trees, rocks, stone lanterns and a pavilion with a detailed tea-ceremony room.Rewind as you craft each beautiful detail and enjoy rearranging the flora to create that perfect look for display in the home or office.',4.7),
    ('price_1O4qKsAu3cUStmz7Mxx2SuSY','Wildflower Bouquet',939,59.99,'18+','https://www.lego.com/cdn/cs/set/assets/bltc4a6c2103a34f22e/10313_alt2.png?format=webply&fit=bounds&quality=70&width=800&height=800&dpr=1.5',7,'Crafted entirely from intricate LEGO pieces, the Wildflower Bouquet features 8 species of wildflowers on adjustable stems. Budding florists and flower lovers can spend hours building and identifying the blooms inspired by cornflowers, lavender, Welsh poppies, cow parsley, leatherleaf ferns, gerbera daisies, larkspur and lupins.',4.9);
    
    
	
	insert into legoMiniFigure (figure_id,figure_name, pieces, image_url, figure_theme_id) values
    (0342,'Luke Skywalker', 4, 'https://img.bricklink.com/ItemImage/MN/0/sw0342.png', 1),
    (0011,'Chewbacca', 3, 'https://img.bricklink.com/ItemImage/MN/0/sw0011.png', 1),
    (1083,'Anakin Skywalker', 4, 'https://img.bricklink.com/ItemImage/MN/0/sw1083.png', 1),
    (0219,'Yoda',3,'https://img.bricklink.com/ItemImage/MN/0/sw0219.png',1),
    (067,'Aladdin',4,'https://img.bricklink.com/ItemImage/MN/0/dp067.png',6),
    (079,'Mulan',4,'https://img.bricklink.com/ItemImage/MN/0/dp079.png',6),
    (164,'Ariel',4,'https://img.bricklink.com/ItemImage/MN/0/dp164.png',6),
    (019,'Mickey Mouse',4,'https://img.bricklink.com/ItemImage/MN/0/dis019.png',6),
    (322,'Albus Dumbledore',5,'https://img.bricklink.com/ItemImage/MN/0/hp147.png',8),
    (176,'Harry Potter',4,'https://img.bricklink.com/ItemImage/MN/0/hp176.png',8),
    (181,'Hermione Granger',4,'https://img.bricklink.com/ItemImage/MN/0/hp181.png',8),
    (287,'Ron Weasley',4,'https://img.bricklink.com/ItemImage/MN/0/hp287.png',8);
    
    
    
	insert into newsPost (post_title, post_caption, date_posted) values
    ('The LEGO Group and Nintendo Bring Animal Crossing™ to LEGO® Brick Form for the First Time', 'The LEGO Group reveals brand-new LEGO® Animal Crossing™ sets, inspired by the popular video game series from Nintendo.', '2023-10-10'),
    ('Today We Play - The LEGO Group Encourages Kids and Adults to Prioritise Play on World Play Day 2023', 'On Thursday, 12th October, the LEGO Group will be hosting its second annual World Play Day – a day dedicated to celebrating the benefits and joy that play brings, and encouraging families around the world to take a moment to play.','2023-10-06'),
    ('The LEGO Group expands Copenhagen Digital Office workspace to meet growing digital team needs', 'The LEGO Group today announced an expansion of its Copenhagen Digital Office a little more than a year after its opening to support the needs of the rapidly growing digital team.', '2023-10-02'),
    ('The LEGO Group remains committed to make LEGO® bricks from sustainable materials', 'We are more committed than ever to making our products and business more sustainable. We have set ambitious targets to reduce carbon emissions, make our products and packaging more sustainable and circular, and run zero impact operation. Over the next three years we plan to triple investment in environmental sustainability, spending more than $1.4 billion on sustainability-related activities.', '2023-09-27');